import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { Task, TaskStatus } from "../types/indes";
import Status from "./tasks/[status]";
import Link from "next/link";
import Quadrant from "../components/Quadrant";

const Home: NextPage = () => {
  const tasks = useState<Task[]>([
    {
      id: 1,
      title: "test",
      status: TaskStatus.UrgentImportant,
    },
    {
      id: 2,
      title: "test",
      status: TaskStatus.UrgentNotImportant,
    },
    {
      id: 3,
      title: "test",
      status: TaskStatus.NotUrgentImportant,
    },
    {
      id: 4,
      title: "test",
      status: TaskStatus.NotUrgentNotImportant,
    },
  ]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Eisenhower Matrix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.row}>
        <Quadrant
          url="urgent-important"
          title="Urgent - Important"
          counter={2}
          counterColor="green"
          description="Urgent and Important tasks demand you take action quickly. These
            items typically have visible deadlines and consequences for stalling
            on taking action. Most often, these are either things that were
            sprung on you from an external source or things that you put off
            until faced with a looming deadline. Either way, they require a
            crisis mode response."
        />
        <Quadrant
          url="not-urgent-important"
          title="Not Urgent - Important"
          counter={4}
          counterColor="blue"
          description="Urgent and Important tasks demand you take action quickly. These
            items typically have visible deadlines and consequences for stalling
            on taking action. Most often, these are either things that were
            sprung on you from an external source or things that you put off
            until faced with a looming deadline. Either way, they require a
            crisis mode response."
        />
      </div>
      <div className={styles.row}>
        <Quadrant
          url="urgent-not-important"
          title="Urgent - Not Important"
          counter={1}
          counterColor="orange"
          description="Urgent and Important tasks demand you take action quickly. These
            items typically have visible deadlines and consequences for stalling
            on taking action. Most often, these are either things that were
            sprung on you from an external source or things that you put off
            until faced with a looming deadline. Either way, they require a
            crisis mode response."
        />
        <Quadrant
          url="urgent-not-important"
          title="Not Urgent - Not Important"
          counter={5}
          counterColor="red"
          description="Urgent and Important tasks demand you take action quickly. These
            items typically have visible deadlines and consequences for stalling
            on taking action. Most often, these are either things that were
            sprung on you from an external source or things that you put off
            until faced with a looming deadline. Either way, they require a
            crisis mode response."
        />
      </div>
    </div>
  );
};

export default Home;
